version: '3.8'
services:
  foundryvttdocker:
    image: foundryvttdocker
    build:
      context: .
      dockerfile: ./Dockerfile
    init: true
    environment:
      FOUNDRY_ADMIN_PASSWORD_FILE: /run/secrets/admin_password
      FOUNDRY_OPTIONS_FILE: /run/secrets/options_file
    secrets:
      - admin_password
      - options_file
    ports:
      - 127.0.0.1:30000:30000
    volumes:
      - vttdata:/home/foundry/fvttdata
    networks:
      - foundryvttnet
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

volumes:
  vttdata:

networks:
  foundryvttnet:

secrets:
  admin_password:
    file: ./.secrets/admin_password
  options_file:
    file: ./.secrets/options.json
