version: '3.08'
services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    command: --config /run/secrets/config
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    ports:
      - 4180:4180/tcp
    networks:
      - foundryvttnet
    secrets:
      - config
      - emails
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

secrets:
  config:
    file: ./.secrets/oauth2_proxy_config
  emails:
    file: ./.secrets/emails.txt

networks:
  foundryvttnet:
    external: true
    name: foundryvtt-docker_foundryvttnet
